import { QA, ModuleItem, DailyMOM } from './types';

export const DEFAULT_QAS: QA[] = [
  { id: '2', name: 'Ajay NR', role: 'Quality Assurance', email: 'ajay@company.com', avatarColor: '#10b981' },
  { id: '3', name: 'R Kusuma', role: 'Quality Assurance', email: 'kusuma@company.com', avatarColor: '#8b5cf6' },
  { id: '4', name: 'Shreyas Peherkar', role: 'Quality Assurance', email: 'shreyas@company.com', avatarColor: '#ec4899' },
  { id: '5', name: 'Rakhi Das', role: 'Executive || Quality Assurance', email: 'rakhi@company.com', avatarColor: '#f59e0b' },
  { id: '6', name: 'Tushar Joshi', role: 'Quality Assurance', email: 'tushar@company.com', avatarColor: '#6366f1' },
  { id: '7', name: 'Indranil Suin', role: 'Quality Assurance', email: 'indranil@company.com', avatarColor: '#14b8a6' },
  { id: '8', name: 'Arka Dastidar', role: 'Quality Assurance', email: 'arka@company.com', avatarColor: '#ef4444' },
];

export const DEFAULT_MODULES: ModuleItem[] = [
  { id: 'm1', name: 'Buyer MY + IM Home' },
  { id: 'm2', name: 'BMC' },
  { id: 'm3', name: 'Android' },
  { id: 'm4', name: 'TDW' },
  { id: 'm5', name: 'Indic IM' },
  { id: 'm6', name: 'FCP/MDC' },
  { id: 'm7', name: 'Whatsapp' },
  { id: 'm8', name: 'BL Form' },
  { id: 'm9', name: 'PNS' },
  { id: 'm10', name: 'MCAT' },
  { id: 'm11', name: 'Enquiry Form' },
];

export const INITIAL_MOM_DATA: DailyMOM = {
  id: '2026-08-05',
  dateFormatted: '05-August-2026',
  createdAt: '2026-08-05T08:00:00.000Z',
  updatedAt: '2026-08-05T08:00:00.000Z',
  attendees: [
    'Ajay NR',
    'R Kusuma',
    'Shreyas Peherkar',
    'Rakhi Das',
    'Tushar Joshi',
    'Indranil Suin',
    'Arka Dastidar',
  ],
  senderName: 'RAKHI DAS',
  senderTitle: 'Executive || Quality Assurance',
  qaTasks: [
    {
      qaId: '5',
      qaName: 'Rakhi Das',
      isOnLeave: false,
      status: 'Working on Launches.',
      tasks: [
        '[MPLaunch@IM] Refreshed Seller Feed homepage (A/B Test) | Buyer MY',
        '[MPLaunch@IM] [MPLaunch@IM] Enhanced Contact Detail Page Experience in BMC',
      ],
    },
    {
      qaId: '7',
      qaName: 'Indranil Suin',
      isOnLeave: false,
      status: 'Working on Launches.',
      tasks: [
        '[MPLaunch@IM] IndiaMART Android App v13.8.4 – MBR Native to WebView Migration',
        '[MPLaunch@IM] IndiaMART Android App Version 13.8.5 [A/B Testing for the "Post Requirement" CTA Landing Screens for SAAB users]',
      ],
    },
    {
      qaId: '8',
      qaName: 'Arka Dastidar',
      isOnLeave: false,
      status: 'Working on Launch.',
      tasks: [
        '[MPLaunch@IM] IndiaMART Android App v13.8.4 – MBR Native to WebView Migration',
      ],
    },
    {
      qaId: '3',
      qaName: 'R Kusuma',
      isOnLeave: false,
      status: 'Working on Launch.',
      tasks: [
        '[MPLaunch@IM] Improved BuyLead Search Experience | Reduced Clarification Step | Paid Sellers | WhatsApp 9696',
      ],
    },
    {
      qaId: '4',
      qaName: 'Shreyas Peherkar',
      isOnLeave: false,
      status: 'Working on Launch.',
      tasks: [
        '[MPLaunch@IM] Hindi.IM | New English Slug URL structure for all INDIC pages',
      ],
    },
    {
      qaId: '2',
      qaName: 'Ajay NR',
      isOnLeave: false,
      status: 'Working on Launch.',
      tasks: [
        '[MPLaunch@IM] Payment Protection Badge on Maximiser | Maximiser Websites',
      ],
    },
    {
      qaId: '6',
      qaName: 'Tushar Joshi',
      isOnLeave: false,
      status: 'working on Kane AI, Product & Seller Ads End-to-end Testing.',
      tasks: [],
    },
  ],
  smokeRows: [
    {
      id: 'sr1',
      module: 'Buyer MY + IM Home',
      qa: 'Rakhi',
      desktopTotal: 138,
      desktopPass: 128,
      desktopFail: 10,
      desktopReport: 'Link',
      desktopReportUrl: '#',
      desktopBugTicketId: 'Link',
      desktopBugTicketUrl: '#',
      msiteTotal: 66,
      msitePass: 60,
      msiteFail: 6,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: 'Link',
      msiteBugTicketUrl: '#',
    },
    {
      id: 'sr2',
      module: 'BMC',
      qa: 'Rakhi',
      desktopTotal: 34,
      desktopPass: 34,
      desktopFail: 0,
      desktopReport: 'Automation report sent',
      desktopBugTicketId: '-',
      msiteTotal: 29,
      msitePass: 29,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr3',
      module: 'Android',
      qa: 'Ajay',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'NA',
      desktopBugTicketId: '-',
      msiteTotal: 50,
      msitePass: 50,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr4',
      module: 'TDW',
      qa: 'Ajay',
      desktopTotal: 23,
      desktopPass: 23,
      desktopFail: 0,
      desktopReport: 'Automation report sent',
      desktopBugTicketId: '-',
      msiteTotal: 33,
      msitePass: 33,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr5',
      module: 'Indic IM',
      qa: 'Shreyas',
      desktopTotal: 40,
      desktopPass: 40,
      desktopFail: 0,
      desktopReport: 'Automation report sent',
      desktopBugTicketId: '-',
      msiteTotal: 29,
      msitePass: 29,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr6',
      module: 'FCP/MDC',
      qa: 'Shreyas',
      desktopTotal: 37,
      desktopPass: 37,
      desktopFail: 0,
      desktopReport: 'Automation report sent',
      desktopBugTicketId: '-',
      msiteTotal: 41,
      msitePass: 41,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr7',
      module: 'Whatsapp',
      qa: 'Kusuma',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'NA',
      desktopBugTicketId: '-',
      msiteTotal: 68,
      msitePass: 66,
      msiteFail: 2,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '680379\n681199',
      msiteBugTicketUrl: '#',
    },
    {
      id: 'sr8',
      module: 'BL Form',
      qa: 'Indranil',
      desktopTotal: 51,
      desktopPass: 50,
      desktopFail: 1,
      desktopReport: 'Link',
      desktopReportUrl: '#',
      desktopBugTicketId: '-',
      msiteTotal: 30,
      msitePass: 30,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr9',
      module: 'PNS',
      qa: 'Indranil',
      desktopTotal: 20,
      desktopPass: 20,
      desktopFail: 0,
      desktopReport: 'Link',
      desktopReportUrl: '#',
      desktopBugTicketId: '-',
      msiteTotal: 22,
      msitePass: 22,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr10',
      module: 'MCAT',
      qa: 'Tushar',
      desktopTotal: 62,
      desktopPass: 62,
      desktopFail: 0,
      desktopReport: 'Automation report sent',
      desktopBugTicketId: '-',
      msiteTotal: 50,
      msitePass: 50,
      msiteFail: 0,
      msiteReport: 'Automation report sent',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr11',
      module: 'Enquiry Form',
      qa: 'Arka',
      desktopTotal: 22,
      desktopPass: 21,
      desktopFail: 1,
      desktopReport: 'Link',
      desktopReportUrl: '#',
      desktopBugTicketId: 'Link',
      desktopBugTicketUrl: '#',
      msiteTotal: 24,
      msitePass: 24,
      msiteFail: 0,
      msiteReport: 'Link',
      msiteReportUrl: '#',
      msiteBugTicketId: '-',
    },
  ],
};
