import { QA, ModuleItem, DailyMOM } from './types';

export const DEFAULT_QAS: QA[] = [
  { id: '2', name: 'Ajay NR', role: 'Quality Assurance', email: 'ajay@company.com', avatarColor: '#10b981' },
  { id: '3', name: 'R Kusuma', role: 'Quality Assurance', email: 'kusuma@company.com', avatarColor: '#8b5cf6' },
  { id: '4', name: 'Shreyas Peherkar', role: 'Quality Assurance', email: 'shreyas@company.com', avatarColor: '#ec4899' },
  { id: '5', name: 'Rakhi Das', role: 'Executive || Quality Assurance', email: 'rakhi@company.com', avatarColor: '#f59e0b' },
  { id: '6', name: 'Tushar Joshi', role: 'Quality Assurance', email: 'tushar@company.com', avatarColor: '#6366f1' },
  { id: '7', name: 'Indranil Suin', role: 'Quality Assurance', email: 'indranil@company.com', avatarColor: '#14b8a6' },
  { id: '8', name: 'Arka Dastidar', role: 'Quality Assurance', email: 'arka@company.com', avatarColor: '#ef4444' },
];

export const DEFAULT_MODULES: ModuleItem[] = [
  { id: 'm1', name: 'Buyer MY + IM Home' },
  { id: 'm2', name: 'BMC' },
  { id: 'm3', name: 'Android' },
  { id: 'm4', name: 'TDW' },
  { id: 'm5', name: 'Indic IM' },
  { id: 'm6', name: 'FCP/MDC' },
  { id: 'm7', name: 'Whatsapp' },
  { id: 'm8', name: 'BL Form' },
  { id: 'm9', name: 'PNS' },
  { id: 'm10', name: 'MCAT' },
  { id: 'm11', name: 'Enquiry Form' },
];

export const INITIAL_MOM_DATA: DailyMOM = {
  id: '2026-08-05',
  dateFormatted: '05-August-2026',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  attendees: [
    'Rakhi Das',
    'Indranil Suin',
    'Arka Dastidar',
    'R Kusuma',
    'Shreyas Peherkar',
    'Ajay NR',
    'Tushar Joshi',
  ],
  senderName: 'RAKHI DAS',
  senderTitle: 'Executive || Quality Assurance',
  qaTasks: [
    { qaId: '5', qaName: 'Rakhi Das', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '7', qaName: 'Indranil Suin', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '8', qaName: 'Arka Dastidar', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '3', qaName: 'R Kusuma', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '4', qaName: 'Shreyas Peherkar', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '2', qaName: 'Ajay NR', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
    { qaId: '6', qaName: 'Tushar Joshi', isOnLeave: false, isSubmitted: false, status: '', tasks: [] },
  ],
  smokeRows: [
    {
      id: 'sr1',
      module: 'Buyer MY + IM Home',
      qa: 'Rakhi',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr2',
      module: 'BMC',
      qa: 'Rakhi',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr3',
      module: 'Android',
      qa: 'Ajay',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'NA',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr4',
      module: 'TDW',
      qa: 'Ajay',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr5',
      module: 'Indic IM',
      qa: 'Shreyas',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr6',
      module: 'FCP/MDC',
      qa: 'Shreyas',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr7',
      module: 'Whatsapp',
      qa: 'Kusuma',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'NA',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr8',
      module: 'BL Form',
      qa: 'Indranil',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr9',
      module: 'PNS',
      qa: 'Indranil',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr10',
      module: 'MCAT',
      qa: 'Tushar',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
    {
      id: 'sr11',
      module: 'Enquiry Form',
      qa: 'Arka',
      desktopTotal: null,
      desktopPass: null,
      desktopFail: null,
      desktopReport: 'Link',
      desktopBugTicketId: '-',
      msiteTotal: null,
      msitePass: null,
      msiteFail: null,
      msiteReport: 'Link',
      msiteBugTicketId: '-',
    },
  ],
};
